[metadata]
name = TracEpicPlugin
version = 1.0.0
author = TracEpicPlugin Contributors
description = Epic <-> ticket linking for Trac 1.6 (M:N relations, changelog, XML-RPC)
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD-3-Clause
classifiers =
    Framework :: Trac
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.13
    License :: OSI Approved :: BSD License

[options]
packages =
    tracepic
python_requires = >=3.9
install_requires =
    Trac>=1.6
zip_safe = false
include_package_data = true

[options.package_data]
tracepic =
    templates/*.html
    htdocs/*.js
    htdocs/*.css

[options.entry_points]
trac.plugins =
    tracepic.api = tracepic.api
    tracepic.web_ui = tracepic.web_ui
    tracepic.xmlrpc = tracepic.xmlrpc
